language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy2.7"
  - "pypy3.5"
# command to install dependencies
install:
  - pip install .[doc,test]
  - mkdir ~/.aci-meta
  - cp meta/aci-meta.limited.json ~/.aci-meta/aci-meta.json
# command to run tests
script: nosetests --cover-tests --with-coverage --cover-html --cover-package=pyaci
